export const SET_MENU_OPTION = "SET_MENU_OPTION";
export const ASSIGN_MENU_OPTION = "ASSIGN_MENU_OPTION";

export const ADD_ITEM = "ADD_ITEM";
export const SET_RECORD = "SET_RECORD";

export const SET_RESULTS = "SET_RESULTS";

export const LOGIN = "LOGIN";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ALERT = "CHANGE_PASSWORD_ALERT";

export const LOAD_ORGANIZATIONS = "LOAD_ORGANIZATIONS";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const SAVE_ORGANIZATION = "SAVE_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";

export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const SAVE_LOCATION = "SAVE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";

export const LOAD_DEPARTMENTS = "LOAD_DEPARTMENTS";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SAVE_DEPARTMENT = "SAVE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const SET_PROJECTS = "SET_PROJECTS";
export const SAVE_PROJECT = "SAVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const LOAD_PROFILES = "LOAD_PROFILES";
export const SET_PROFILES = "SET_PROFILES";

export const LOAD_STATUS = "LOAD_STATUS";
export const SET_STATUS = "SET_STATUS";

export const LOAD_USERS = "LOAD_USERS";
export const SET_USERS = "SET_USERS";
export const SAVE_USER = "SAVE_USER";
export const DELETE_USER = "DELETE_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
